WSUCEG-7140/TeamH

- .github/workflows/testing.yml
- requirements.txt
> Issue#18 setup automated testing configuration

- PatientInfoapp/tests.py
Testing patient_healthinfo table
> Issue#20 testing patient healthinfo table

- PatientInfoapp/urls.py
- PatientInfoapp/views.py
Created add_patient end point in views.py
> Issue#3 insert endpoint

- PatientInfoapp/views.py
Creating edit api end point in views.py for updating the patient details
> Issue#9 update endpoint

- PatientInfoapp/urls.py
- PatientInfoapp/views.py
created remove api endpoint for removing the specific patient data
> Issue#6 remove endpoint

- PatientInfoapp/Templates/PatientInfoapp/home.html
Added edit button in home page.
> Added edit button

- PatientInfoapp/Templates/PatientInfoapp/home.html
created view button in home page
> Added view tab

- PatientInfoapp/Templates/PatientInfoapp/home.html
created delete button in home page.
> added delete button

- PatientInfoapp/Templates/PatientInfoapp/add_patient.html
created navigation bar in addpatient page.
> Added navigation bar in addpatient page

- PatientInfoapp/Templates/PatientInfoapp/add_patient.html
Added General Info and health info fields in add patient page.
> Added health info and general info fields

- PatientInfoapp/Templates/PatientInfoapp/edit_patient.html
Added title for 'Update Patient Record' page and links for using Bootstrap classes.
> Adding title for page and links for using Bootstrap

- PatientInfoapp/Templates/PatientInfoapp/edit_patient.html
Added logo to the edit patient page.
> added logo in edit page

- PatientInfoapp/Templates/PatientInfoapp/edit_patient.html
added navigation bar with home, Admin, and Add patient in edit patient page
> Added home,Add patient,Admin in edit patient page

- PatientInfoapp/Templates/PatientInfoapp/edit_patient.html
added edit patient details functionality in the edit patient page.
> added edit patient details functionality

- PatientInfoapp/Templates/PatientInfoapp/patient_detail.html
Added title for 'Display Patient Record' page.
> Added title for display_patient_record page

- PatientInfoapp/Templates/PatientInfoapp/patient_detail.html
created logo in patient details view page.
> Added logo in patient view page

- PatientInfoapp/Templates/PatientInfoapp/patient_detail.html
Added header with navigation links to home, add patient and admin pages.
> added navigation bar with home, add patient, admin

- PatientInfoapp/Templates/PatientInfoapp/patient_detail.html
added general info table which will display the information in the webpage when clicked on view button.
> general info view in display page

- PatientInfoapp/Templates/PatientInfoapp/patient_detail.html
created health information in display webpage displays the health information of patient when clicked view button.
> HealthInfo in view page

- PatientInfoapp/.gitignore
> added git ignore file

- PatientInfoapp/tests.py
created view test case for checking patient details
> View test case

- PatientInfoapp/tests.py
Added a test case for checking invalid form submission.
> Test case for invalid submission

- README.md
Added the Readme file for application.
> Added the README file

- PatientInfoapp/templates/PatientInfoapp/add_patient.html
- PatientInfoapp/templates/PatientInfoapp/edit_patient.html
- PatientInfoapp/templates/PatientInfoapp/home.html
- PatientInfoapp/tests.py
- PatientInfoapp/views.py
Added comments in views.py and tests.py
> Comments in the code were added

- Minutes_Of_Meeting/MOM-1.md
- Minutes_Of_Meeting/MOM-2.md
- README.md
created Minutes of meeting for sprint -1
> Sprint#1 mom

- Minutes_Of_Meeting/MOM-3.md
- Minutes_Of_Meeting/MOM-4.md
created Minutes of Meeting for Sprint#2
> Sprint#2 mom

- Doxyfile
- README.md
Updated the doxyfile and excluded the migrations directory in code documentation.
> Updated the doxyfile

- PatientInfoapp/views.py
- README.md
Added Doc strings in views.py which has @brif,@param,@pre and @post structured comments.
> Added Doc Strings in views.py which satisfy Program of contract & literate Programming

- Requirements.md
> Added Requirements.md file

- design.md
> Added design.md file.

- PatientInfoapp/models.py
> comments for models.py

- PatientInfoapp/forms.py
> comments for forms.py

- PatientInfoapp/tests.py
Updated the DocStrings for setUp and models testcases.
> Updated the DocStrings for models testcases.

- PatientInfoapp/tests.py
DocStrings for Add,View and delete functions in test.py file
> Added DocStrings for Add,View,Delete

- PatientInfoapp/tests.py
Updated docStrings for Search, Edit, Invalidform testcases.
> Updated docStrings for Search_Edit_Invalidform testcases
